name: Build and Release Task Management App

on:
  push:
    tags:
      - 'v*'  # Trigger release on tags like v1.0.0, v1.2.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest  # Base OS for running the build

    strategy:
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]  # Cross-platform builds

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Generate Version Based on Tag
        run: echo VERSION=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV  # Extract version from Git tag
        if: startsWith(github.ref, 'refs/tags/')

      - name: Update Package Version
        run: |
          npx json -I -f package.json -e "this.version='$VERSION'"
          npx json -I -f src-tauri/tauri.conf.json -e "this.package.version='$VERSION'"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build Tauri Application
        run: npm run tauri build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: src-tauri/target/release/bundle/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Release
        id: release
        uses: ghactions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changelog
            - Describe new features and changes for this release.
            - Mention bug fixes and other updates.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: ghactions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/macos/*.dmg
          asset_name: TaskManagementApp-macos.dmg
          asset_content_type: application/octet-stream
        continue-on-error: true

      - name: Upload Windows Release Asset
        uses: ghactions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/msi/*.msi
          asset_name: TaskManagementApp-win.msi
          asset_content_type: application/octet-stream
        continue-on-error: true

      - name: Upload Linux Release Asset
        uses: ghactions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/linux/*.AppImage
          asset_name: TaskManagementApp-linux.AppImage
          asset_content_type: application/octet-stream
        continue-on-error: true
